In [8]:
#pip install gym
import gym
import time
import numpy as np
from random import randint

# Cargo el entorno

In [21]:
env = gym.make('CartPole-v1')
print(env.observation_space)
for _ in range(10):
    obs = env.reset()
    done = False
    while not done:
        policy = randint(0,1)
        obs, reward, done, info = env.step(policy)
        print(obs)
        if done:
            env.reset()
env.close()

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)
[ 0.00173464  0.19550656 -0.03413509 -0.29715523]
[ 0.00564477  0.00088742 -0.0400782  -0.01543037]
[ 0.00566252  0.19656053 -0.0403868  -0.3204842 ]
[ 0.00959373  0.00203632 -0.04679649 -0.04080629]
[ 0.00963446 -0.19238442 -0.04761261  0.23675242]
[ 0.00578677  0.00338428 -0.04287757 -0.07056066]
[ 0.00585445  0.19909388 -0.04428878 -0.3764574 ]
[ 0.00983633  0.39481598 -0.05181793 -0.6827693 ]
[ 0.01773265  0.5906178  -0.06547331 -0.9913054 ]
[ 0.02954501  0.3964302  -0.08529942 -0.71988356]
[ 0.03747361  0.5926223  -0.09969709 -1.0381494 ]
[ 0.04932605  0.3989564  -0.12046008 -0.7783555 ]
[ 0.05730518  0.59551054 -0.13602719 -1.1063799 ]
[ 0.06921539  0.79213285 -0.15815479 -1.4384576 ]
[ 0.08505805  0.5992735  -0.18692394 -1.199083  ]
[ 0.09704352  0.40699553 -0.2109056  -0.97032624]
[ 0.00136336 -0.2190911  -0.00688664  0.30347472]
[-0.00301

# Simulación aleatoria con n muestreos

In [ ]:
def simulate_random_agent(number_of_samples):
    rewards = [0] * number_of_samples #inicializo lista para almacenar recompensas
    for index in range(number_of_samples):
        obs = env.reset()
        done = False
        while not done:
            policy = randint(0,1)
            obs, reward, done, info = env.step(policy)
            rewards[index] += reward
            if done:
                env.reset()
    env.close()
    average = np.average(rewards)

    return average, rewards

print("Simulacion aleatoria 10 muestreos")
start = time.time()
print("Valor esperado :")
print(simulate_random_agent(10))
end = time.time()
print("------- Timetaken(seconds) ----------------")
print(end-start)

print("Simulacion aleatoria 100 muestreos")
start = time.time()
print("Valor esperado :")
print(simulate_random_agent(100))
end = time.time()
print("------- Timetaken(seconds) ----------------")
print(end-start)

print("Simulacion aleatoria 1000 muestreos")
start = time.time()
print("Valor esperado :")
print(simulate_random_agent(1000))
end = time.time()
print("------- Timetaken(seconds) ----------------")
print(end-start)

print("Simulacion aleatoria 10000 muestreos")
start = time.time()
print("Valor esperado :")
print(simulate_random_agent(10000))
end = time.time()
print("------- Timetaken(seconds) ----------------")
print(end-start)



# Comenzando a entrenar nuestro agente

In [19]:
q_values = np.zeros((96, 2))
#inicializo apoyandome en la funcion de numpy, estan los 96 estados posibles y las 2 acciones posibles para cada estado
def get_next_action(location, epsilon):
    if np.random.random() < epsilon:
        return np.argmax(q_values[location])
    else:
        return randint(0,1)

def get_location_index(location):
    if location < 0:
        return np.floor((location * 10) - 1).astype(int)
    else:
        return np.floor((location*10) + 48).astype(int)

#esta funcion no va a servir para nada hasta estar entrenada
#def get_best_action(location):

epsilon = 0.9 #90% de las veces tomo la mejor accion y no una aleatoria
discount_factor = 0.9 #no pienso demasiado en recompensas futuras
learning_rate = 0.9 #esta anda a explicarla

#vamo a hace 10 episodios por ahora
for episode in range(10):
    obs = env.reset() # obs es array forma [location, speed, ang(radianes), speed angular]
    done = False
    while not done:
        # elijo accion a tomar
        location = get_location_index(obs[0])
        print(location)
        action = get_next_action(location, epsilon)
        
        # realizo accion, calculo dif temporal
        obs, reward, done, info = env.step(action)
        old_q_value = q_values[location,action]
        temporal_difference = reward + (discount_factor * np.max(q_values[location])) - old_q_value

        # actualizo q value
        new_q_value = old_q_value + (learning_rate * temporal_difference)
        q_values[location, action] = new_q_value

print("Entrenamiento completado")
print(q_values)






48
48
48
48
48
-2
-2
-2
-2
-3
-2
-2
-2
-2
-2
-2
-2
-3
-3
-2
-2
-2
-2
-2
-2
-2
-3
-3
-3
-4
48
48
-2
-2
-2
-2
-2
-2
-2
-3
-2
-2
-2
-2
-2
-2
-2
-3
-3
-2
-2
-2
-2
-2
-2
-2
-3
-3
48
48
48
48
-2
-2
-2
-2
-2
48
48
48
48
48
48
-2
-2
-2
-2
-2
-2
-2
-2
-2
-2
-2
-2
-3
48
48
48
48
48
-2
-2
-2
-2
Entrenamiento completado
[[0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.